# Generated by Django 4.2.7 on 2025-09-13 19:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("curriculum", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="course",
            name="thumbnail",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="course_thumbnails/",
                verbose_name="Course Thumbnail",
            ),
        ),
    ]
